repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks: 
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks: 
      - id: ruff
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks: 
      - id: gitleaks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks: 
      - id: detect-secrets