version: '3.8'

services:
  montage-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montage-staging
    environment:
      - ENVIRONMENT=staging
      - CANARY_VERSION=phase2-dual-import
      - PROMETHEUS_PUSHGATEWAY_URL=http://prometheus-pushgateway:9091
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - prometheus
      - prometheus-pushgateway
    networks:
      - montage-staging

  redis:
    image: redis:7-alpine
    container_name: montage-redis-staging
    ports:
      - "6380:6379"
    networks:
      - montage-staging

  prometheus:
    image: prom/prometheus:latest
    container_name: montage-prometheus-staging
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - montage-staging

  prometheus-pushgateway:
    image: prom/pushgateway:latest
    container_name: montage-pushgateway-staging
    ports:
      - "9092:9091"
    networks:
      - montage-staging

networks:
  montage-staging:
    driver: bridge