version: "3.9"
services:
  postgres:
    image: postgres:15
    environment: { POSTGRES_PASSWORD: pass }  # pragma: allowlist secret
    ports: ["5432:5432"]
  redis:
    image: redis:7.2-alpine
    ports: ["6379:6379"]
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]