# Kubernetes namespace for AI Video Processing Pipeline
apiVersion: v1
kind: Namespace
metadata:
  name: video-pipeline
  labels:
    name: video-pipeline
    app.kubernetes.io/name: video-pipeline
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: ai-video-pipeline
    app.kubernetes.io/managed-by: kubectl
---
# Resource quota to prevent resource exhaustion
apiVersion: v1
kind: ResourceQuota
metadata:
  name: video-pipeline-quota
  namespace: video-pipeline
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
# Network policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: video-pipeline-network-policy
  namespace: video-pipeline
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector: {}
  egress:
  - {} # Allow all egress traffic