# Kubernetes Secret for Montage API Keys
# This will be populated by Vault Agent or External Secrets Operator
apiVersion: v1
kind: Secret
metadata:
  name: montage-secrets
  namespace: montage
  labels:
    app: montage
    component: secrets
type: Opaque
data:
  # These will be base64 encoded by Vault integration
  # For manual creation: echo -n "your-key" | base64
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""  
  DEEPGRAM_API_KEY: ""
  GEMINI_API_KEY: ""
---
# External Secrets Operator configuration (if using ESO)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore  
metadata:
  name: vault-backend
  namespace: montage
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "montage"
          secretRef:
            name: "vault-token"
            key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: montage-vault-secrets
  namespace: montage
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: montage-secrets
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: montage/openai
      property: OPENAI_API_KEY
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: montage/anthropic  
      property: ANTHROPIC_API_KEY
  - secretKey: DEEPGRAM_API_KEY
    remoteRef:
      key: montage/deepgram
      property: DEEPGRAM_API_KEY
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: montage/gemini
      property: GEMINI_API_KEY