apiVersion: v1
kind: Service
metadata:
  name: montage-async-pool-canary
  namespace: montage-staging
spec:
  selector:
    app: montage
    version: async-pool-canary
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
