name: Config Guard

on:
  push:
    branches: [ main, develop, phase-* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  enforce-single-config-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Enforce single config source
        run: |
          if grep -R "secret_loader" montage/ | grep -v tests; then
            echo "Legacy config detected"; exit 1; fi